data_science_web_urls = ['https://www.onlinemanipal.com/blogs/data-science-use-cases-in-finance',
                         'https://www.altexsoft.com/blog/datascience/how-to-structure-data-science-team-key-models-and-roles/',
                         'https://www.techtarget.com/searchbusinessanalytics/feature/How-to-structure-and-manage-a-data-science-team/',
                         'https://datatalks.club/blog/building-data-science-team.html',
                         'https://www.indeed.com/career-advice/career-development/how-to-manage-data-science-team',
                         'https://www.springboard.com/blog/data-science/learn-data-science-on-your-own',
                         'https://www.springboard.com/blog/data-science/how-to-become-a-data-scientist/',
                         'https://www.knowledgehut.com/blog/data-science/data-science-team-structure',
                         'https://hbr.org/2018/10/managing-a-data-science-team',
                         'https://hbr.org/2023/04/generative-ai-will-change-your-business-heres-how-to-adapt',
                         'https://hbr.org/2023/05/what-does-it-actually-take-to-build-a-data-driven-culture',
                         'https://hbr.org/2023/06/the-ai-hype-cycle-is-distracting-companies',
                         'https://hbr.org/2012/10/data-scientist-the-sexiest-job-of-the-21st-century',
                         'https://developers.google.com/machine-learning/guides/good-data-analysis',
                         'https://thecleverprogrammer.com/2023/09/05/steps-to-solve-a-data-science-problem/',
                         'https://towardsdatascience.com/how-to-self-learn-data-science-in-2022-a537a76d138e',
                         'https://abdullahsaka.medium.com/lessons-learned-the-common-mistakes-in-data-science-1456ede09783',
                         'https://towardsdatascience.com/5-lessons-i-have-learned-from-data-science-in-real-working-experience-3532c1b41fd7',
                         'https://www.simplilearn.com/how-big-data-can-help-do-wonders-in-business-rar398-article',
                         'https://www.simplilearn.com/data-science-vs-big-data-vs-data-analytics-article',
                         'https://www.vortech.nl/en/guidelines-for-a-successful-data-science-project/']

data_science_youtube_urls = ['https://www.youtube.com/watch?v=xC-c7E5PK0Y']

finance_gpt_urls = ['https://datasciencedojo.com/blog/large-language-models-finance/',
                    'https://datasciencedojo.com/blog/large-language-models-finance/',
                    'https://www.turintech.ai/2023/07/27/llms-financial-industry/',
                    'https://towardsdatascience.com/how-to-harness-the-power-of-data-science-in-finance-4b5335a98507',
                    'https://a-teaminsight.com/blog/the-rise-of-large-language-models-in-financial-markets/?brand=tti',
                    'https://snorkel.ai/poll-data-llm-high-priority-enterprise-data-science-concerns-remain/',
                    'https://medium.com/@Railwaymen_org/how-to-build-fintech-software-development-team-a5d56b922600',
                    'https://fintech.global/2023/08/02/chat-gpt-and-other-llms-are-being-rapidly-adopted-by-fintech-companies/']

others_urls = ['https://stfalcon.com/en/blog/post/challenges-in-fintech-software-development',
               'https://sdk.finance/fintech-development-challenges/',
               'https://www.devteam.space/blog/fintech-software-development-how-to-build-the-right-team/',
               'https://www.masthead.co.za/newsletter/using-fintech-to-your-advantage/',
               'https://www.valuecoders.com/blog/blockchain-ml/chatgpt-use-cases-in-software-development/',
               'https://www.linkedin.com/pulse/excited-share-how-perform-code-review-using-chatgpt-khadar-basha',
               'https://www.linkedin.com/pulse/top-6-data-science-pain-points-2021-david-yakobovitch',
               'https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/unleashing-developer-productivity-with-generative-ai',
               'https://towardsdatascience.com/training-soft-skills-in-data-science-with-real-life-simulations-a-role-playing-dual-chatbot-c80dec3dd08c']